# Site settings
title: "macoso"
bye_message: "/dev/null"
baseurl: "/"
url: "http://macoso.blur.tech"
disqus: macoso

# Header settings
nick: "macoso"
mail:
    domain: "blur"
    ext: "tech"
source_code:
    server: "github.com"
    nick: "macoso"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-twitter-plugin
  - jemoji
  - jekyll-seo-tag
twitter:
    username: batyshkaLenin
    card: summary
social:
  name: Александр Сидоренко
  links:
    - https://twitter.com/batyshkaLenin
    - https://vk.com/alexandr_sidorenko
    - http://instagram.com/alexander_sidorenko/
    - http://github.com/MacOSO
lang: ru_RU